#ifndef DEVICE_IDENTITY_DEVICE_IDENTITY_THREAD_INCLUDE_H
#define DEVICE_IDENTITY_DEVICE_IDENTITY_THREAD_INCLUDE_H

#include "../../internal/03-thread/01-DeviceIdentityThread.h"

#endif // DEVICE_IDENTITY_DEVICE_IDENTITY_THREAD_INCLUDE_H
