#ifndef DEVICE_IDENTITY_IDEVICE_DIAGNOSTICS_INCLUDE_H
#define DEVICE_IDENTITY_IDEVICE_DIAGNOSTICS_INCLUDE_H

#include "../../internal/00-public/02-IDeviceDiagnostics.h"

#endif // DEVICE_IDENTITY_IDEVICE_DIAGNOSTICS_INCLUDE_H