#ifndef DEVICE_IDENTITY_DEVICE_IDENTITY_THREAD_PUBLIC_H
#define DEVICE_IDENTITY_DEVICE_IDENTITY_THREAD_PUBLIC_H

#include "../01-interface/01-IDeviceIdentityProvider.h"

#endif // DEVICE_IDENTITY_DEVICE_IDENTITY_THREAD_PUBLIC_H
