#ifndef DEVICE_IDENTITY_DEVICE_TIME_SYNC_THREAD_PUBLIC_H
#define DEVICE_IDENTITY_DEVICE_TIME_SYNC_THREAD_PUBLIC_H

#include "../01-interface/02-IDeviceTimeSyncScheduler.h"

#endif // DEVICE_IDENTITY_DEVICE_TIME_SYNC_THREAD_PUBLIC_H
