#ifndef DEVICE_IDENTITY_IDEVICE_DIAGNOSTICS_PUBLIC_H
#define DEVICE_IDENTITY_IDEVICE_DIAGNOSTICS_PUBLIC_H

#include "../01-interface/03-IDeviceDiagnostics.h"

#endif // DEVICE_IDENTITY_IDEVICE_DIAGNOSTICS_PUBLIC_H